PIXEL_ORDER: 1
PIXEL_MEANS: [0.485, 0.456, 0.406]
PIXEL_VARS:  [0.229, 0.224, 0.225]
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
  MASK_ON: True
  LOAD_IMAGENET_PRETRAINED_WEIGHTS: False
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  USE_SN: True  # Note: use SN on the FPN-specific layers
  SN:
    USE_BN: False
RESNETS:
  FREEZE_AT: 2
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_sn_transformation  # Note: this is a SN bottleneck transform
  STEM_FUNC: basic_sn_stem  # Note: this is a SN stem
  SHORTCUT_FUNC: basic_sn_shortcut  # Note: this is a SN shortcut
  USE_SN: True
  SN:
    USE_BN: False
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_Xconv1fc_sn_head  # Note: this is a Conv SN head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
  SN:
    USE_BN: False
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs_sn  # Note: this is a SN mask head
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
  SN:
    USE_BN: False
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 20000
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
