PIXEL_ORDER: 1
PIXEL_MEANS: [0.485, 0.456, 0.406]
PIXEL_VARS:  [0.229, 0.224, 0.225]
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: True
  LOAD_IMAGENET_PRETRAINED_WEIGHTS: False
RESNETS:
  FREEZE_AT: 0
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_sn_transformation  # Note: this is a SN bottleneck transform
  STEM_FUNC: basic_sn_stem  # Note: this is a SN stem
  SHORTCUT_FUNC: basic_sn_shortcut  # Note: this is a SN shortcut
  USE_SN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 2)
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 2
  BATCH_SIZE_PER_IM: 256
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
